[versions]
agp = "8.5.0"
kotlin = "1.9.23"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.12.0" }